<?php

/**
 * @file
 *   Integrates Mollom with Facebook-style Statuses.
 */

/**
 * Implementation of hook_mollom_form_list().
 */
function fbss_mollom_mollom_form_list() {
  return array(
    'facebook_status_box' => array(
      'title' => t('Facebook-style Statuses update status form'),
      'entity' => 'facebook_status',
      'report access' => array(
        'post status messages to other streams',
        'update and view own stream',
      ),
      'report delete callback' => 'facebook_status_delete_status',
    ),
    'facebook_status_edit' => array(
      'title' => t('Facebook-style Statuses edit status form'),
      'entity' => 'facebook_status',
      'report access' => array(
        'delete all statuses',
        'delete own statuses',
        'delete status messages on own profile',
        'delete status messages on own nodes',
      ),
      'report delete callback' => 'facebook_status_delete_status',
    ),
  );
}

/**
 * Implementation of hook_mollom_form_info().
 */
function fbss_mollom_mollom_form_info($form_id) {
  if ($form_id == 'facebook_status_box') {
    return array(
      'title' => t('Facebook-style Statuses update status form'),
      'mode' => MOLLOM_MODE_ANALYSIS,
      'bypass access' => array(
        'delete all statuses',
        'edit all statuses',
        'send messages to all users at once',
      ),
      'elements' => array('fbss-status' => t('Status box')),
      'mapping' => array(
        'post_title' => 'fbss-status',
      ),
    );
  }
  elseif ($form_id == 'facebook_status_edit') {
    return array(
      'title' => t('Facebook-style Statuses edit status form'),
      'mode' => MOLLOM_MODE_ANALYSIS,
      'bypass access' => array(
        'delete all statuses',
        'edit all statuses',
        'send messages to all users at once',
      ),
      'entity' => 'facebook_status',
      'elements' => array('fbss-status' => t('Status box')),
      'mapping' => array(
        'post_id' => 'sid',
        'post_title' => 'fbss-status',
      ),
    );
  }
}
