<?php
// $Id: userpoints_invite.install,v 1.3 2008/11/07 02:59:38 kbahey Exp $

define('USERPOINTS_INVITE_REGISTER',         'userpoints_invite_register');
define('USERPOINTS_INVITE_REGISTER_INVITER', 'userpoints_invite_register_inviter');
define('USERPOINTS_INVITE_REGISTER_INVITEE', 'userpoints_invite_register_invitee');

/**
 * An update schema - renames the USERPOINTS_INVITE_REGISTER variable to USERPOINTS_INVITE_REGISTER_INVITER
 */
function userpoints_invite_update_1() {
  $var = variable_get(USERPOINTS_INVITE_REGISTER, 'unset');
  if ($var != 'unset') {
    variable_del(USERPOINTS_INVITE_REGISTER);
    variable_set(USERPOINTS_INVITE_REGISTER_INVITER, $var);
  }
}
