<?php
/**
 * @file
 * Code for the Commons Posts feature.
 */

include_once 'commons_posts.features.inc';

function commons_posts_commons_bw_group_widget() {
  return array(
    'commons_posts' => array(
      'title' => 'Posts',
      'type' => 'view',
      'vid' => 'commons_bw_posts',
      'display' => 'page_1',
      'weight' => 5,
    ),
  );
}

function commons_posts_views_pre_render(&$view) {
  if ($view->name == 'commons_bw_posts' && user_access('Post: Create new content')) {
    $group_id = $view->args[0];
    $view->attachment_before = l('Create a post', 'node/add/post', array('query' => array('og_group_ref' => $group_id)));
  }  
 }

/**
* Implements hook_strongarm_alter().
*   Expose the Post content type for 'liking' via the Commons_likem module
*   by altering the configuration for the Rate.module widget that it provides.
*/
 function commons_posts_strongarm_alter(&$items) {
  if (!empty($items['rate_widgets']->value)) {
    foreach($items['rate_widgets']->value as $key => $widget) {
      if ($widget->name == 'commons_like') {
        $items['rate_widgets']->value[$key]->node_types[] = 'post';
        $items['rate_widgets']->value[$key]->comment_types[] = 'post';
      }
    }
  }
}

/**
* Implements hook_commons_radioactivity_field().
*   Add field_radioactivity to the Post content type.
*/
function commons_posts_commons_radioactivity_field() {
  return 'post';
}