<?php

/**
 * Implements hook_block_info().
 */
function commons_utility_links_block_info() {
  $blocks['commons_utility_links'] = array(
    'info' => t('Commons utility links'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function commons_utility_links_block_view() {
  $block['subject'] = '';
  $block['content'] = '';
  $links = array();

  if (user_is_logged_in()) {
    global $user;
    $account = $user;
    $links['name'] = array(
      'href' => 'user',
      'title' => format_username($account),
    );
    $links['logout'] = array(
      'href' => 'user/logout',
      'title' => t('Logout'),
    );
  }
  else {
    if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
      $links['signup'] = array(
        'href' => 'user/register',
        'title' => t('Signup'),
      );
    }
    $links['login'] = array(
      'href' => 'user/login',
      'title' => t('Login'),
    );
  }
  drupal_alter('commons_utility_links', $links);
  $block['content'] = theme('links', array('links' => $links, 'attributes' => array('class' => 'commons-utility-links')));
  return $block;
}
