<?php
/**
 * @file
 * Code for the Commons Posts feature.
 */

include_once 'commons_posts.features.inc';

/**
* Implements hook_commons_bw_group_widget().
*/
function commons_posts_commons_bw_group_widget() {
  return array(
    'commons_posts' => array(
      'title' => 'Posts',
      'type' => 'view',
      'vid' => 'commons_bw_posts',
      'display' => 'page_1',
      'weight' => 5,
    ),
  );
}

/**
* Implements hook_views_pre_render().
*/
function commons_posts_views_pre_render(&$view) {
  if ($view->name == 'commons_bw_posts' && user_access('Post: Create new content')) {
    $group_id = $view->args[0];
    $view->attachment_before = l('Create a post', 'node/add/post', array('query' => array('og_group_ref' => $group_id)));
  }  
 }

/**
* Implements hook_strongarm_alter().
*/
 function commons_posts_strongarm_alter(&$items) {
  // Expose the Post content type for 'liking' via the Commons_like module
  // by altering the configuration for the Rate.module widget that it provides.
  if (!empty($items['rate_widgets']->value)) {
    foreach($items['rate_widgets']->value as $key => $widget) {
      if ($widget->name == 'commons_like') {
        if (!in_array('post', $items['rate_widgets']->value[$key]->node_types)) {
          $items['rate_widgets']->value[$key]->node_types[] = 'post';  
        }       
        if (!in_array('post', $items['rate_widgets']->value[$key]->comment_types)) {
          $items['rate_widgets']->value[$key]->comment_types[] = 'post';  
        }
      }
    }
  }
  // Expose the post content type for integration with Commons Radioactivity
  // and Commons Groups.  
  foreach (array('commons_radioactivity_entity_types', 'commons_groups_entity_types') as $key) {
    if (isset($items[$key])) {  
      $items[$key]->value['node']['post'] = 1;
    }
  }
}
