<?php
/**
 * @file
 * Code for the Commons Q&A feature.
 */

include_once 'commons_q_a.features.inc';

/**
* Implements hook_commons_bw_group_widget().
*/
function commons_q_a_commons_bw_group_widget() {
  return array(
    'commons_q_a' => array(
      'title' => 'Q & A',
      'type' => 'view',
      'vid' => 'commons_q_a_questions_in_a_group',
      'display' => 'default',
      'weight' => 5,
    ),
  );
}

/**
* Implements hook_views_pre_render().
*/
function commons_q_a_views_pre_render(&$view) {
  if ($view->name == 'commons_q_a_questions_in_a_group') {
    $group_id = $view->args[0];
    if (og_user_access('node', $group_id, 'create question content')) {
      $view->attachment_before = l(t('Ask a question'), 'node/add/question', array('query' => array('og_group_ref' => $group_id)));
    }
  }
  if ($view->name == 'commons_question_answers' && !empty($view->args[0])) {
    // If the user has access to post into any of the groups associated
    // with the question, embed a simplified answer node form.
    $question_nid = $view->args[0];
    $question = node_load($question_nid);
    foreach ($question->og_group_ref[LANGUAGE_NONE] as $key => $value) {
      if (og_user_access('node', $value['target_id'], 'create answer content')) {
        module_load_include('inc', 'node', 'node.pages');
        global $user;
        $types = node_type_get_types();
        $node = (object) array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => 'answer', 'language' => LANGUAGE_NONE);
        // Prepopulate the Related question field
        // with Entityreference Prepopulate, which looks strictly at $_GET.
        $_GET['field_related_question'] = '20';
        $answer_form = drupal_get_form('answer_node_form', $node);
        $answer_form['header'] = array(
          '#markup' => '<h3>' . t('Add a new answer') . '</h3>',
          '#weight' => -10,
        );
        // Hide any vertical tabs that might be present.
        $answer_form['additional_settings']['#access'] = FALSE;
        // Hide the Related question field.
        $answer_form['field_related_question']['#access'] = FALSE;
        // Add the form to the attachment_after part of the view,
        $view->attachment_after .= drupal_render($answer_form);
        // We only need to add the form once if the user has access to
        // post questions into any of the groups associated with the parent.
        return;
      }
    }
  }
}

/**
* Implements hook_form_alter().
*/
function commons_q_a_form_alter(&$form, &$form_state, $form_id) {
  // Unset the groups audience field. Answers programatically inherit
  // the group membership of their respective questions.
  if ($form_id == 'answer_node_form') {
    $form['og_group_ref']['#access'] = FALSE;
  }
  if ($form_id == 'question_node_form' && empty($form['node']->nid)) {
    drupal_set_title(t('Ask a question'));
  }
}

/**
 * Implements hook_field_attach_submit().
 */
function commons_q_a_field_attach_submit($entity_type, &$entity, $form, &$form_state) {
  // Questions should inherit the group membership of the related question.
  if ($entity_type == 'node' && $entity->type == 'answer' && empty($entity->nid)) {
    $question = node_load($entity->field_related_question[LANGUAGE_NONE][0]['target_id']);
    $entity->og_group_ref[LANGUAGE_NONE] = $question->og_group_ref[LANGUAGE_NONE];
  }
}

/**
 * Implements hook_commons_entity_integration.
 */
function commons_q_a_commons_entity_integration() {
  return array(
    'node' => array(
      'question' => array(
      ),
      'answer' => array(
      ),
    ),
  );
}

function commons_q_a_commons_activity_streams_message_selection_alter(&$message_type, $hook, $node) {
  //$a = func_get_args();
  //dpm($a, 'and args');
  if ($hook == 'node_insert' && $node->type == 'question') {
    $message_type = 'commons_q_a_question_asked';
  }
}
