<?php
/**
 * @file
 * Code for the Commons Wikis feature.
 */

include_once 'commons_wikis.features.inc';

/**
 * Implements hook_menu_alter().
 */
function commons_wikis_menu_alter(&$items) {
  $items['node/%node/revisions']['access callback'] = 'commons_wikis_user_revision_access';
}

/**
 * Custom access callback for viewing revision info.
 */
function commons_wikis_user_revision_access($node) {
  if ($node->type == 'wiki') {
    return TRUE;
  }
  else {
    return user_access('view revisions');
  }
}

/**
 * Implements hook_commons_bw_group_widget().
 */
function commons_wikis_commons_bw_group_widget() {
  return array(
    'commons_wikis' => array(
      'title' => t('Wikis'),
      'type' => 'view',
      'vid' => '',
      'display' => '',
      'weight' => 8,
    ),
  );
}
