<?php
/**
 * @file
 * Code for the Commons Q&A feature.
 */

include_once 'commons_q_a.features.inc';

/**
* Implements hook_commons_bw_group_widget().
*/
function commons_q_a_commons_bw_group_widget() {
  return array(
    'commons_q_a' => array(
      'title' => 'Q & A',
      'type' => 'view',
      'vid' => 'commons_q_a_questions_in_a_group',
      'display' => 'default',
      'weight' => 5,
    ),
  );
}


/**
 * Implements hook_commons_entity_integration.
 */
function commons_q_a_commons_entity_integration() {
  return array(
    'node' => array(
      'question' => array(
      ),
      'answer' => array(
      ),
    ),
  );
}
