<?php
/**
 * commons_search.module
 * Code for the Commons Search feature.
 */

include_once 'commons_search.features.inc';

/**
 * Implements hook_module_implements_alter().
 */
function commons_search_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    // We move commons_search to the end so it gets processed last.
    $group = $implementations['commons_search'];
    unset($implementations['commons_search']);
    $implementations['commons_search'] = $group;
  }
}

/**
 * Custom search form that switches between Core and Solr depending on which is
 * the enabled search module.
 */
function commons_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    // Move the textfield to after the drop down.
    $site_key = 'c-all';
    $form['search_block_form']['#weight'] = 1;
    if (module_exists('apachesolr_search')) {
      $site_key = 'o-solr';
    }
    $form['custom_search_types']['#options'] = array(
      $site_key => t('Site'),
      'c-user' => t('Users'),
    );
    $group = FALSE;
    $node = current_path();
    if (strpos($node, 'node/') !== FALSE
      && is_numeric(substr($node, strpos($node, '/')+1))) {
      $node = node_load(substr($node, strpos($node, '/')+1));
      dsm($node);
      if (property_exists($node, 'og_group_ref')) {
        $group = TRUE;
      }
    }
    if ($group) {
      $form['custom_search_types']['#options']['c-group'] = t('Group');
    }
  }
}

/**
 * Implements hook_search_info().
 */
function commons_search_search_info() {
  return array(
    'title' => t('Commons Search - Group Search'),
    'path' => '',
    'conditions_callback' => 'commons_search_conditions',
  );
}

/**
 * Return search conditions to search within the current group.
 */
function commons_search_conditions($keys) {
  if (module_exists('apachesolr_search')) {
    $conditions['fq'] = '';
  }
  return $conditions;
}

/**
 * Implements hook_search_execute().
 */
function commons_search_search_execute($keys = NULL, $conditions = NULL) {
  if (module_exists('apachesolr_search')) {
    return apachesolr_search_search_execute($keys, $conditions);
  }
  else {
    return search_search_execute($keys, $conditions);
  }
}
