<?php

/**
 * Disable summary on Posts nodes.
 */
function commons_posts_update_7000() {
    $revert = array(
      'commons_posts' => array('field_instance'),
  );
  features_revert($revert);
  return array();
}

/**
 * Provide a new "User posted [title]" message type for posts.
 */
function commons_posts_update_7001() {
    $revert = array(
      'commons_posts' => array('message_type', 'field_instance'),
  );
  features_revert($revert);
  return array();
}