<?php
/**
 * @file
 * Code for the Commons polls feature.
 */

include_once 'commons_polls.features.inc';

/**
* Implements hook_commons_bw_group_widget().
*/
function commons_polls_commons_bw_group_widget() {
  return array(
    'commons_polls' => array(
      'title' => 'Polls',
      'type' => 'view',
      'vid' => 'commons_bw_polls',
      'display' => 'default',
      'weight' => 10,
    ),
  );
}

/**
 * Implements hook_commons_bw_create_all_widget().
 */
function commons_polls_commons_bw_create_all_widget($group) {
  if (og_user_access('node', $group->nid, 'create poll content')) {
    $link = l(t('Create a poll'),'node/add/poll',
    array('attributes' => array('class' => 'commons-polls-create'), 'query' => array('og_group_ref' => $group->nid))
    );
    return array(
      'commons_polls' => array(
        'default' => TRUE,
        'link' => $link,
        'text' =>  t('Measure opinions on a topic'),
        '#weight' => -1,
      ),
    );
  }
}


/**
 * Implements hook_commons_entity_integration.
 */
function commons_polls_commons_entity_integration() {
  return array(
    'node' => array(
      'poll' => array(
      ),
    ),
  );
}

/**
* Implements hook_views_pre_render().
*/
function commons_polls_views_pre_render(&$view) {
  if ($view->name == 'commons_bw_polls') {
    $group_id = $view->args[0];
    if (og_user_access('node', $group_id, 'create poll content')) {
      $view->attachment_before = l(t('Create a poll'), 'node/add/poll', array('query' => array('og_group_ref' => $group_id)));
    }
  }
}

/**
* Implements hook_strongarm_alter().
*/
 function commons_polls_strongarm_alter(&$items) {
  // Expose the poll content type for 'liking' via the Commons_like module
  // by altering the configuration for the Rate.module widget that it provides.
  if (!empty($items['rate_widgets']->value)) {
    foreach($items['rate_widgets']->value as $key => $widget) {
      if ($widget->name == 'commons_like') {
        if (!in_array('poll', $items['rate_widgets']->value[$key]->node_types)) {
          $items['rate_widgets']->value[$key]->node_types[] = 'poll';
        }
        if (!in_array('poll', $items['rate_widgets']->value[$key]->comment_types)) {
          $items['rate_widgets']->value[$key]->comment_types[] = 'poll';
        }
      }
    }
  }
  // Expose the poll content type for integration with Commons Radioactivity
  // and Commons Groups.
  foreach (array('commons_radioactivity_entity_types', 'commons_groups_entity_types') as $key) {
    if (isset($items[$key])) {
      $items[$key]->value['node']['poll'] = 1;
    }
  }
}
