<?php
/**
 * @file
 * Code for the Commons Wikis feature.
 */

include_once 'commons_wikis.features.inc';

/**
 * Implements hook_menu_alter().
 */
function commons_wikis_menu_alter(&$items) {
  // Find all menu items that are related to viewing a revision and change the
  // access callback to our custom one.
  foreach ($items as $route => $info) {
    if (strpos($route, 'revisions') !== FALSE
      && strpos($route, 'revert') === FALSE
      && strpos($route, 'delete') === FALSE) {
      $items[$route]['access callback'] = 'commons_wikis_user_revision_access';
    }
  }
}

/**
 * Custom access callback for viewing revision info.
 */
function commons_wikis_user_revision_access($node = NULL) {
  global $user;
  if ($node->type == 'wiki') {
    return TRUE;
  }
  else {
    return user_access('view revisions', $user);
  }
}

/**
 * Implements hook_commons_bw_group_widget().
 */
function commons_wikis_commons_bw_group_widget() {
  return array(
    'commons_wikis' => array(
      'title' => t('Wikis'),
      'type' => 'view',
      'vid' => 'commons_bw_wikis',
      'display' => 'default',
      'weight' => 8,
    ),
  );
}
