<?php

include_once('commons_status_streams.features.inc');

/**
 * Implementation of hook_menu().
 */
function commons_status_streams_menu() {
  $items = array();
  $items['stream'] = array(
    'title' => 'Activity stream',
    'page callback' => 'commons_status_streams_stream_page',
    'access callback' => TRUE,
    'description' => 'An activity dashboard page.',
    'file' => 'commons_status_streams.pages.inc',
  );
  return $items;
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function commons_status_streams_form_system_site_information_settings_alter(&$form, $form_state) {
  $form['commons_status_streams_auth_frontpage'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use the activity stream as the front page for authenticated users'),
    '#description' => t('If enabled, users who get to the front page by clicking your site name or logo or who are directed to the front page by Drupal will be redirected to their activity stream at <code>/stream</code> if they are logged in. Users can still visit the "normal" front page that anonymous users see by visiting its path directly or by clicking on the "Home" link in the menu.'),
    '#default_value' => variable_get('commons_status_streams_auth_frontpage', 1),
  );
  $form['buttons']['#weight'] = 10;
}

/**
 * Implementation of hook_init().
 */
function commons_status_streams_init() {
  if (variable_get('commons_status_streams_auth_frontpage', 1) && !user_is_anonymous()) {
    // example.com requested, but not example.com/home
    if (!str_replace(base_path(), '', $_SERVER['REQUEST_URI'])) {
      drupal_goto('stream');
    }
  }
}
