<?php
// $Id: mollom_test.install,v 1.1.2.2 2010/10/16 18:24:54 sun Exp $

/**
 * @file
 * Installation functionality for Mollom testing module.
 */

/**
 * Implements hook_schema().
 */
function mollom_test_schema() {
  $schema['mollom_test'] = array(
    'description' => 'Stores testing data for Mollom test form.',
    'fields' => array(
      'mid' => array(
        'description' => 'Primary key: Unique mollom_test entity ID.',
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'title' => array(
        'description' => 'Title of the post.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'body' => array(
        'description' => 'Body of the post.',
        'type' => 'text',
        'not null' => TRUE,
      ),
      'status' => array(
        'description' => 'Publishing status.',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 1,
      ),
    ),
    'primary key' => array('mid'),
  );
  return $schema;
}

/**
 * Implements hook_install().
 */
function mollom_test_install() {
  drupal_install_schema('mollom_test');
}

/**
 * Implements hook_uninstall().
 */
function mollom_test_uninstall() {
  drupal_uninstall_schema('mollom_test');
}

