<?php

include_once('commons_core.features.inc');

/**
 * Implementation of hook_content_default_fields_alter()
 * 
 * Alter the default cck fields right before they are cached into the database.
 *
 * @param &$fields
 *   By reference. The fields that have been declared by another feature.
 */
function commons_core_content_default_fields_alter(&$fields) {
  // Dynamically set the group default image path to the
  // current files directory
  if (isset($fields['group-field_group_image'])) {
    $fields['group-field_group_image']['widget']['default_image']['filepath'] = file_directory_path() . '/default-group.png';
    $fields['group-field_group_image']['widget']['default_image']['destination'] = file_directory_path() . '/default-group.png';
  }
}

/**
 * Implementation of hook_perm()
 */
function commons_core_perm() {
  return array('view content rss feeds', 'view group content rss feeds');
}

/**
 * Implementation of hook_menu()
 */
function commons_core_menu() {  
  return array(
    'myprofile' => array(
      'title' => 'My profile',
      'description' => 'View your user profile',
      'page callback' => 'commons_core_profile_redirect',
      'access callback' => 'user_is_logged_in',
      'type' => MENU_CALLBACK,
    ),
    'community' => array(
      'title' => 'Community',
      'description' => 'View the groups in the community',
      'page callback' => 'commons_core_community_redirect',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    ),
    'admin/settings/commons' => array(
      'title' => 'Drupal Commons',
      'description' => 'Configure settings for the Drupal Commons environment',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('commons_core_admin_settings'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implemenation of hook_admin_settings()
 */
function commons_core_admin_settings() {
  $form = array();
  
  $form['general_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('General settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  
  $form['general_settings']['commons_force_login'] = array(
    '#type' => 'checkbox',
    '#title' => t('Force users to login'),
    '#default_value' => variable_get('commons_force_login', 0),
    '#description' => t('If checked, anonymous users will be redirected from all pages to a log in page.'),
  );
  
  $form['general_settings']['commons_recent_join_interval'] = array(
    '#type' => 'select',
    '#title' => t('Recent joins time-frame'),
    '#default_value' => variable_get('commons_recent_join_interval', '3 months'),
    '#options' => array(
      '3 days' => '3 days',
      '1 week' => '1 week',
      '2 weeks' => '2 weeks',
      '1 month' => '1 month',
      '3 months' => '3 months',
      '6 months' => '6 months',
    ),
    '#description' => t('The !user_directory contains a block that indicates the amount of recently joined members. Select the time-frame to be used to calculate this value.', array('!user_directory' => l(t('user directory'), 'users'))),
  );
  
  $form['general_settings']['commons_manager_role'] = array(
    '#type' => 'textfield',
    '#title' => t('Community manager role'),
    '#required' => TRUE,
    '#default_value' => variable_get('commons_manager_role', 'community manager'),
    '#description' => t('The name of the role given to community managers.'),
  );
  
  $form['group_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Group settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  
  $form['group_settings']['commons_group_tab_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Group homepage tab'),
    '#default_value' => variable_get('commons_group_tab_title', 'Home'),
    '#description' => t('Specify what the group homepage tab title should be. If left empty, the tab title will be <i>View</i>.'),
  );
  
  $form['group_settings']['commons_force_unique_groups'] = array(
    '#type' => 'checkbox',
    '#title' => t('Force unique group names'),
    '#default_value' => variable_get('commons_force_unique_groups', 1),
    '#description' => t('If checked, group names must be unique. This will not affect existing groups.'),
  );
  
  $form['group_settings']['commons_hide_shoutbox_link'] = array(
    '#type' => 'checkbox',
    '#title' => t('Remove Shoutbox link'),
    '#default_value' => variable_get('commons_hide_shoutbox_link', 1),
    '#description' => t('If checked, the Shoutbox link will be removed from the Group details menu.'),
  );
  
  $form['group_settings']['commons_email_selective_group'] = array(
    '#type' => 'checkbox',
    '#title' => t('Alert users when added to a selective group'),
    '#default_value' => variable_get('commons_email_selective_group', 1),
    '#description' => t('If checked, an email alert will be sent to users that are added to groups that are marked as either invite-only or closed.'),
  );
  
  $form['group_settings']['commons_group_admin_edit_comments'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow group admins to edit all group comments'),
    '#default_value' => variable_get('commons_group_admin_edit_comments', 0),
    '#description' => t('If checked, group admins will have the ability to edit any comments on content items inside their groups.'),
  );
  
  $form['group_settings']['commons_group_prevent_open_voting'] = array(
    '#type' => 'checkbox',
    '#title' => t('Restrict voting to group members'),
    '#default_value' => variable_get('commons_group_prevent_open_voting', 0),
    '#description' => t('If checked, only group members will be able to vote on polls that are part of a given group.'),
  );
  
  $form['group_settings']['commons_group_prevent_open_commenting'] = array(
    '#type' => 'checkbox',
    '#title' => t('Restrict commenting to group members'),
    '#default_value' => variable_get('commons_group_prevent_open_commenting', 0),
    '#description' => t('If checked, only group members will be able to comment on nodes that are part of a given group.'),
  );

  return system_settings_form($form); 
}

/**
 * Implementation of hook_menu_alter()
 */
function commons_core_menu_alter(&$items) {
  // Override group node tab title from 'View' to 'Home'
  $items['node/%node/view']['title callback'] = 'commons_core_set_node_tab_title';
  $items['node/%node/view']['title arguments'] = array(1);
  
  // Move OG_Aggregator menu tab to far right
  $items['node/%node/aggregator']['weight'] = 100;
  
  // (Optionally) override comment edit permissions
  $items['comment/edit']['page callback'] = 'commons_core_comment_edit';
}

/**
 * Callback for group node tab titles
 */
function commons_core_set_node_tab_title($node) {
  if (og_is_group_type($node->type)) {
    return variable_get('commons_group_tab_title', t('Home'));
  }
  
  return t('View');
}

/**
 * Optionally remove Shoutbox link from Group menu
 */
function commons_core_og_links_alter(&$links, &$node) {
  // Optionally hide the shoutbox link
  if (variable_get('commons_hide_shoutbox_link', 1)) {
    unset($links['shoutbox']);
  }
  
  // Change the Manager item to a link to our managers page
  if (isset($links['manager'])) {
    $group = og_get_group_context();
    $links['manager'] = l(t('Group managers'), "og/users/{$group->nid}/managers");
  }
}

/**
 * Implementation of hook_block()
 */
function commons_core_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('User statistics'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    $blocks[1] = array(
      'info' => t('Jumpstart your community!'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    $blocks[2] = array(
      'info' => t('Drupal Commons information'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    $blocks[3] = array(
      'info' => t('Header login block'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    $blocks[4] = array(
      'info' => t('Join & learn more'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    $blocks[5] = array(
      'info' => t('Group actions'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    $blocks[6] = array(
      'info' => t('Subscribe to user being viewed'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );

    return $blocks;
  }
  else if ($op == 'view') {
    switch($delta) {
      case 0:
        $block = array(
          'subject' => t('User statistics'),
          'content' => _commons_core_user_stats_block()
        );
        break;
      case 1:
        $block = array(
          'subject' => t('Jumpstart your community!'),
          'content' => _commons_core_jumpstart_community_block()
        );
        break;
      case 2:
        $block = array(
          'subject' => '',
          'content' => theme('commons_core_info_block')
        );
        break;
      case 3:
        $block = array(
          'subject' => '',
          'content' => _commons_core_header_login_block()
        );
        break;
      case 4:
        $block = array(
          'subject' => t('Join & learn more'),
          'content' => _commons_core_join_block()
        );
        break;
      case 5:
        $details = og_block_details();
        if (isset($details['content'])) {
          $block = array(
            'subject' => t('Actions'),
            'content' => $details['content']
          );
        }
        break;
      case 6:
        $block = array(
          'subject' => '',
          'content' => _commons_core_subscribe_to_user_profile_block()
        );
        break;
    }
    return $block;
  }  
}

/**
 * Display a block with global user statistics
 */
function _commons_core_user_stats_block() {
  $data = array();
  
  // Determine total users on the site
  $total = db_result(db_query("SELECT COUNT(uid) FROM {users} WHERE status = 1"));
  $data[] = format_plural($total, '1 user', '@count users');
  
  // Determine recently joined users
  $total = db_result(db_query("SELECT COUNT(uid) FROM {users} WHERE status = 1 AND created > %d", strtotime('-' . variable_get('commons_recent_join_interval', '3 months'), time())));
  $data[] = format_plural($total, '1 recently joined member', '@count recently joined members');
  
  return theme('commons_core_user_stats_block', $data);
}

/**
 * Display "jumpstart" block
 */
function _commons_core_jumpstart_community_block() {
  return t('!view, or !create new groups to start creating your community!', array('!view' => l(t('View'), 'groups'), '!create' => l(t('create'), 'node/add/group')));
}

/**
 * Display our custom login block for the header
 */
function _commons_core_header_login_block() {
  global $user;
  
  // Only anonymous users can log in
  if ($user->uid) {
    return NULL;
  }
  
  // No login needed if we're on the login page
  if (arg(0) == 'user') {
    return NULL;
  }
  
  // Determine if we're on the front page
  if (drupal_is_front_page()) {
    // Only provide a link
    return t('Already a member? !login', array('!login' => l(t('Login'), 'user')));
  }
  
  // Render the standard login form
  return drupal_get_form('user_login_block');
}

/**
 * The "Join & learn more" registration block callback
 */
function _commons_core_join_block() {
  // Check access
  if (!user_register_access()) {
    return NULL;
  }
  
  return drupal_get_form('commons_core_join_form');
}

/**
 * The "Join & learn more" registration form
 */
function commons_core_join_form() {
  $form = array();
  
  // Pull the standard user registration form
  $rform = user_register();
  
  // Extract required profile fields
  foreach ($rform as $key => $profile) {
    if (is_array($profile)) {
      foreach ($profile as $pkey => $pfield) {
        if (substr($pkey, 0, 8) == 'profile_') {
          if ($pfield['#required']) {
            // Remove description
            unset($pfield['#description']);
            // Add to our form
            $form[$pkey] = $pfield;
          }
          unset($rform[$key][$pkey]);
        }
      }
    }
  } 
  
  // Extract needed account elements
  foreach ($rform['account'] as $key => $field) {
    if (is_array($field) && $field['#required']) {
      // Remove the description
      unset($field['#description']);
      // Add to our form
      $form[$key] = $field;
    }
  }
  unset($rform['account']);
  
  // Shorten the email field (if available)
  if (isset($form['mail'])) {
    $form['mail']['#title'] = t('Email');
  }
  
  // Copy the registration validators
  $form['#validate'] = $rform['#validate'];
  
  // Attach the registration submit callback
  $form['#submit'] = array('user_register_submit');
  
  // Add the submit button
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Join our community'),
  );
  
  return $form;
}

/**
 * Provide a block that contains a link to subscribe to the
 * user being viewed
 */
function _commons_core_subscribe_to_user_profile_block() {
  global $user;
  
  // Current user must be logged in
  if ($user->uid) {
    // Must be viewing a user who is not the currnet user
    if (arg(0) == 'user' && is_numeric(arg(1)) && $user->uid != arg(1) && $account = user_load(arg(1))) {
      // Notifications UI must be enabled
      if (module_exists('notifications_ui')) {
        // Check notification settings
        if (notifications_ui_account_options('links') && ($options = notifications_ui_subscribe_options($user, 'user', $account))) {
          $links = notifications_ui_build_links($options);
          return theme('links', $links, array('class' => 'item-list'));
        }
      }
    }
  }
}

/**
 * Helper function to provide node add links
 * 
 * @param $type
 *   The machine-name of the node
 * @return
 *   A link to add a new node, if permissions allow
 */
function commons_core_node_add_link($type) {
  global $user;
  
  // Determine the name of the node type, and see if it's valid
  if (!($name = node_get_types('name', $type))) {
    return NULL;
  }
  
  // First detect normal node permissions
  if (!node_access('create', $type)) {
    return NULL;
  }
  
  // Detect a group context
  if (og_is_group_post_type($type)) {
    if ($group = commons_core_get_group_context()) {
      // No access if the user is not logged in
      if (!$user->uid) {
        return NULL;
      }
      // No access if the user is not a member
      else if (!og_is_group_member($group->nid, TRUE, $user->uid)) {
        // Unless they are a community manager
        if (!array_search(variable_get('commons_manager_role', 'community manager'), $account->roles)) {
          return NULL;
        }
      }
    }
  }
  
  // Build the link
  $link = array();
  $link['title'] = t('Add a new !name', array('!name' => $name));
  $link['href'] = "node/add/$type";
  
  // Add group URL query, if needed
  if ($group) {
    $link['options'] = array(
      'query' => "gids[]={$group->nid}",
    );
  }
  
  // Generate the link
  $link = l($link['title'], $link['href'], isset($link['options']) ? $link['options'] : array());
  
  return theme('commons_core_node_add_link', $link);
}

/**
 * Detect a group context
 * This function is more robust than just og_get_group_context()
 *
 * @param $node
 *   Optionally specify a node being viewed
 * @return
 *   A group object if available, otherwise NULL
 */
function commons_core_get_group_context($node = NULL) {
  static $group = FALSE;
  
  if ($group === FALSE) { 
    // Get group context
    if (!($group = og_get_group_context())) {
      // If group context not yet set, see if we can get it from the URL
      if (is_numeric(arg(1))) {
        $node = $node ? $node : node_load(arg(1));
        if ($node) {
          if (!og_is_group_type($node->type)) {
            // If we pulled a node that isn't a group, see if the node is
            // inside a group
            if ($groups = og_get_node_groups($node)) {
              // Use the first group
              $group = node_load(key($groups));
            }
          }
          else {
            $group = $node;
          }
        }
      }
      // The node add form URL queries might help
      else if (arg(0) == 'node' && arg(1) == 'add' && arg(2)) {
        $gids = $_GET['gids'];
        if (is_array($gids)) {
          $gid = $gids[0];
          if (is_numeric($gid)) {
            if ($node = node_load($gid)) {
              if (og_is_group_type($node->type)) {
                $group = $node;
              }
            }
          }
        }
      }
    }
  }

  return $group;
}

/**
 * Implementation of hook_form_alter()
 */
function commons_core_form_alter(&$form, &$form_state, $form_id) {
  // A node is being added or edited
  if (strstr($form_id, 'node_form')) {
    // Load the node
    $node = $form['#node'];
    
    // Remove default "Promoted to Front Page" option
    unset($form['options']['promote']);
  
    // Check if this is a group type
    if (module_exists('og')) {
      if (og_is_group_type($node->type)) {
        // Make user's aware of the max length
        $maxlength = $form['og_description']['#maxlength'];
        $form['og_description']['#description'] = $form['og_description']['#description'] . ' (' . t('!maxlength characters allowed', array('!maxlength' => $maxlength)) . ')'; 
      
        // Groups don't have titles, they have names
        $form['title']['#title'] = t('Name');
      }
    }
  }

  // Optionally restrict voting only to members of the group
  // that the poll is in
  if ($form_id == 'poll_view_voting') {
    // Check the variable
    if (variable_get('commons_group_prevent_open_voting', 0)) { 
      // Extract the poll node itself
      $poll = $form['#node'];
        
      commons_core_group_restrict_form($poll, $form, t('vote'), array('vote'));
    }
  }
  
  // Optionally restrict commenting only to members of the group that
  // the node is in
  if ($form_id == 'comment_form') {
    // Check the variable
    if (variable_get('commons_group_prevent_open_commenting', 0)) { 
      // Determine the node
      // The node ID is either located at node/id or comment/reply/id
      $node = (arg(0) == 'node') ? node_load(arg(1)) : node_load(arg(2));  
        
      // Make sure the node loaded correctly
      if ($node) {
        commons_core_group_restrict_form($node, $form, t('comment'));
      }
    }
  }
  
  // Views bulk operations form
  // Use strstr() because the form_id contains a suffix
  if (strstr($form_id, 'views_bulk_operations_form')) {
    // Move operation controls above the content
    $form['submit']['#weight'] = -100; 
  }
}

/**
 * Alter a form based on the current user's group membership status
 * 
 * If the current user is not a member of any of the given group(s)
 * associated with the $node, then remove $elements from the form
 * 
 * @param $node
 *   The group post node
 * @param $form
 *   The form to alter, passed in as reference
 * @param $action
 *   A string representing the action that is being prevented (Eg, comment)
 * @param $elements
 *   The form element identified to remove. If omitted, the entire form will be
 *   removed
 */
function commons_core_group_restrict_form($node, &$form, $action, $elements = array()) {
  // Make sure OG is enabled  
  if (!module_exists('og')) {
    return; 
  }
  
  //Determine which groups the poll belongs to
  $groups = og_get_node_groups($node);
        
  // Only act if this poll is part of a group
  if (count($groups)) {
    $access = FALSE;
          
    // Iterate through the groups, checking for membership
    foreach ($groups as $id => $name) {
      if (og_is_group_member($id)) {
        // Indicate that the user is a member of at least one group
        $access = TRUE;
        break; 
      }
    }
        
    // If the user isn't a member of any of the groups, they can't
    // vote on this poll
    if (!$access) {
      // Unset the specified elements
      if (empty($elements)) {
        // If non specified, remove the whole form
        $form = '';
      }
      else {
        foreach ($elements as $element) {
          unset($form[$element]);
        }
      }
      
      //Let user know why they can't act
      $form['denied_message'] = array(
        '#type' => 'item',
        '#value' => t('You must be a member of the group to !action', array('!action' => $action)),
      );
    } 
  }
}

/**
 * Implementation of hook_og()
 */
function commons_core_og($op, $gid, $uid, $args) {
  switch ($op) {
    case 'user insert':
    case 'user delete':
      // Load the group object
      $group = node_load($gid);
      og_load_group($group);
      
      // Load the user
      $user = user_load($uid);
      
      // Should we try to send an email alert?
      if (variable_get('commons_email_selective_group', 1)) {
        // Don't act if this is the group creator
        if ($group->uid != $user->uid) {
          // Only act if the group is invite-only or closed
          if ($group->og_selective == OG_INVITE_ONLY ||
            $group->og_selective == OG_CLOSED) {
            // Send the email alert
            drupal_mail(
              'commons',
              "og $op",
              $user->mail,
              language_default(),
              array('group' => $group)
            );
          }
        }
      }
      
      break;
  }
}

/**
 * Implementation of hook_mail()
 */
function commons_core_mail($key, &$message, $params) {
  switch ($key) {
    case 'og user delete':
      $message['subject'] = t('You have been removed from !group', array('!group' => $params['group']->title));
      $message['body'] = t('A manager from !group has removed you from the group.', array('!group' => $params['group']->title));
      break;
    
    case 'og user insert':
      global $base_url;
      $link = $base_url . '/' . ($params['group']->path ? $params['group']->path : ('node/' . $params['group']->nid));
      $message['subject'] = t('You have been added to !group', array('!group' => $params['group']->title));
      $message['body'] = t('A manager from !group has added you to the group.', array('!group' => $params['group']->title));
      $message['body'] .= "\n\n\n";
      $message['body'] .= t('The group is located at !link', array('!link' => $link));
      break;
  }
}

/**
 * Implementation of hook_field_access()
 */
function commons_core_field_access($op, $field, $account = NULL, $node = NULL) {
  if ($field['field_name'] == 'field_group_sticky') {
    switch($op) {
      case 'view':
      case 'edit':
        // If on node add form, use og_get_group_context() to determine group
        if (arg(0) == 'node' && arg(1) == 'add' && ($group = commons_core_get_group_context())) {
          // hook_nodeapi() validates group admin status if additional
          // groups are selected
          
          // Show only under the following conditions
          if (!og_is_group_admin($group, $account) && 
              !user_access('administer nodes') && 
              !array_search(variable_get('commons_manager_role', 'community manager'), $account->roles)) {
          
            return FALSE;
          }
          else {
            return TRUE;
          }
        }
      
        /**
         * If here, we're now viewing the node. Must handle access controls
         * for editablefields.module
         */

        if ($node) {
          // Determine all group affiliations for the current node
          $groups = og_get_node_groups($node);
          
          // If no group affiliates, never show
          if (empty($groups)) {
            return FALSE;
          }
          
          // Users with admin nodes permission and community manager role can always edit
          if (user_access('administer nodes') || array_search(variable_get('commons_manager_role', 'community manager'), $account->roles)) {
            return TRUE;
          }

          // Check that current user is the admin of all groups
          foreach ($groups as $nid => $group) {
            if (!og_is_group_admin(node_load($nid))) {
              return FALSE;
            }
          }
        }
        
        return TRUE;
    }
  }
}

/**
 * Implementation of hook_init()
 */
function commons_core_init() {
  // Exit if coming from the command-line (needed for drush),
  // if we're not calling index.php (so cron.php, xmlrpc.php, etc, works),
  // of if the site is in maintenance mode
  if ((php_sapi_name() == 'cli') ||
    (str_replace(base_path(), '', $_SERVER['SCRIPT_NAME']) != 'index.php') ||
    variable_get('site_offline', 0)) {
    return;
  }

  //  Force anonymous users to a login page
  if (variable_get('commons_force_login', 0)) {
    global $user;
  
    // If anonymous
    if (!$user->uid) {
      //  Avoid endless redirect and allow for user registration/creation/login
      //  Checking arg(1) for numeric value prevents /user/# path
      if (arg(0) != 'user' || is_numeric(arg(1))) {
        // Redirect to home
        if ($dest = $_GET['q']) {
          // If the user was trying to reach a certain page,
          // try to preserve the redirection after login
          drupal_goto('user', "destination=$dest");
        }
        else {
          drupal_goto('user');
        }
      }
    }
  }
  
  // We've overridden /og with a custom view, so redirect
  if (arg(0) == 'og' && !arg(1)) {
    drupal_goto('groups');
  }
  
  // We've overridden /og/my with a custom view, so redirect
  if (arg(0) == 'og' && arg(1) == 'my') {
    drupal_goto('groups/my');
  }
  
  // Redirect core /profile which lists users to our new list of users
  if (arg(0) == 'profile' && !arg(1)) {
    drupal_goto('users');
  }
  
  // Notify group admins of any pending requests on group home page
  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
    // Load the current user
    global $user;
    
    // Check to see if user is logged in
    if ($user->uid) {
      // Load the current node
      $node = node_load(arg(1));
      // Determine if this is a group
      if (og_is_group_type($node->type)) {
        // Check if current member is an admin
        if (og_is_group_admin($node, $user)) {
          // Check if there are pending requests
          $count = db_result(db_query("
            SELECT COUNT(uid) FROM {og_uid} 
            WHERE nid = %d AND is_active = 0", $node->nid));
            
          if ($count) {
            drupal_set_message(t('There are currently !count pending membership requests. Click !here to view them.', array('!count' => $count, '!here' => l('here', 'og/users/' . $node->nid))));
          }
        }
      }
    }
  }
  
  // Set the breadcrumbs
  commons_core_set_breadcrumb($_GET['q']);
}

/**
 * Dynamically set the breadcrumbs
 * 
 * Commons ships with a large amount of panels, views,
 * and dynamic content. This result in missing or incorrect
 * breadcrumbs.
 * 
 * @param $path
 *   The requested path (Eg, node/2)
 */
function commons_core_set_breadcrumb($path) {
  $breadcrumb = array();
  
  // Break the path into pieces
  $path = explode('/', $path);
  
  switch ($path[0]) {
    case 'taxonomy':
      $breadcrumb[] = l(t('Tags'), 'tagadelic');
      break;
      
    case 'content':
      if ($path[1]) {
        $breadcrumb[] = l(t('Community'), 'groups'); 
      }
      break;
    
    case 'notices':
    case 'featured':
    case 'userpoints':
    case 'users':
    case 'analytics':
    case 'tagadelic':
      $breadcrumb[] = l(t('Community'), 'groups');
      break;
      
    case 'groups':
      if ($path[1]) {
        $breadcrumb[] = l(t('Groups'), 'groups'); 
      }
      break;
      
    case 'group':
    case 'bookmarks':
    case 'relationships':
    case 'myuserpoints':
    case 'mycontent':
      $breadcrumb[] = l(t('My account'), 'user');
      break;
      
    case 'node':
      if (is_numeric($path[1])) {
        switch ($path[2]) {
          case 'content':
          case 'aggregator':
            $group = node_load($path[1]);
            $breadcrumb[] = l(t('Groups'), 'groups');
            $breadcrumb[] = l($group->title, 'node/' . $group->nid);
            break;
        }
      }
      break;
      
    case 'og':
      if (is_numeric($path[2])) {
        switch ($path[1]) {
          case 'users':
          case 'search':
          case 'subscribe':
            $group = node_load($path[2]);
            $breadcrumb[] = l(t('Groups'), 'groups');
            $breadcrumb[] = l($group->title, 'node/' . $group->nid); 
        }
      }
      break;
  }
  
  // Check if we've added any breadcrumbs
  if (!empty($breadcrumb)) {
    // If so, add a frontpage link to the beginning
    array_unshift($breadcrumb, l(t('Home'), '<front>'));
    
    // And set them
    drupal_set_breadcrumb($breadcrumb);
  }
}

/**
 * Menu callback helper to provide a menu item which redirects to the
 * current user's profile.
 * 
 * We need this because Features can't export sublinks on a menu if a
 * sublink has the same path as the menu root
 */
function commons_core_profile_redirect() {
  global $user;
  drupal_goto("user/{$user->uid}");
}

/**
 * Menu callback helper to provide a menu item which redirects to the
 * communities page.
 * 
 * We need this because Features can't export sublinks on a menu if a
 * sublink has the same path as the menu root
 */
function commons_core_community_redirect() {
  drupal_goto("groups");
}

/**
 * Implementation of hook_nodeapi()
 */
function commons_core_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'validate':
      // Make sure the "group sticky" field was used correctly
      commons_core_check_group_sticky($node);
      
      // Make sure group titles are unique
      commons_core_check_group_title($node);
      
      break;
  }
}

/*
 * Enforce the rules of the "group sticky" field
 * 
 * This function is called when validating a node. If the "group sticky'
 * field is checked, we make sure that the current user is the admin
 * of all groups the node belongs to. A form error is thrown if the
 * user shouldn't be setting this field.
 * 
 * @param $node
 *   The node being validated
 */
function commons_core_check_group_sticky($node) {
  global $user;
  
  // Only act if the node was toggled as sticky
  if ($node->field_group_sticky[0]['value'] == 'Sticky') {
    $selected_groups = array();
    
    // Gather checked group ids, if any
    if (isset($node->og_groups)) {
      foreach ($node->og_groups as $gid) {
        // Capture only checked groups
        if ($gid) {
          $selected_groups[] = $gid;
        }
      }
    }

    // Check if any group options were checked
    if (!empty($selected_groups)) {
      // If inadequate permissions & roles, then check for group admin status in each group
      if (!user_access('administer nodes') && !array_search(variable_get('commons_manager_role', 'community manager'), $user->roles)) {
        foreach ($selected_groups as $gid) {
          if (!og_is_group_admin(node_load($gid), $user)) {
            form_set_error('og_groups', t('You can only make posts sticky for the groups that you are an admin for.')); 
          }
        }
      }
    }
    else {
      // No groups were selected
      form_set_error('field_group_sticky', t('You must specify a group in order to make this post group sticky.')); 
    }
  }
}

/*
 * Force unique group titles
 * 
 * @param $node
 *   The node being validated
 */
function commons_core_check_group_title($node) {
  // Check if we're enforcing unique group titles 
  if (variable_get('commons_force_unique_groups', 1)) {
    // Check that this is a group node
    if (og_is_group_type($node->type)) {
      // See if a group with this title already exists
      $sql = "SELECT n.nid FROM {node} n INNER JOIN {og} o ON o.nid = n.nid WHERE n.title = '%s' AND n.nid != %d";
      $existing = db_fetch_object(db_query($sql, $node->title, $node->nid));
      if ($existing) {
        form_set_error('title', t('A group already exists with that name. Please choose another.')); 
      }
    }
  }
}

/**
 * Implementation of hook_views_pre_view()
 */
function commons_core_views_pre_view(&$view, &$display_id, &$args) {
  switch ($view->name) {
    case 'og_my_groups':
    case 'og_all':
    case 'og_most_active':
      $view->display_handler->override_option('header', commons_core_node_add_link('group'));
      break;
      
    case 'recent_notices':
      $view->display_handler->override_option('header', commons_core_node_add_link('notice'));
      break;
      
    case 'tag_cloud':
      $view->display_handler->override_option('footer', l(t('View more'), 'tagadelic'));
      break;
      
    case 'recent_featured_stream':
      $view->display_handler->override_option('footer', l(t('View all featured content'), 'featured'));
      break;
  }
}

/**
 * Implementation of hook_form_views_exposed_form_alter()
 */
function commons_core_form_views_exposed_form_alter(&$form, &$form_state) {
  switch ($form['#id']) {
    // The "My unread" tab on the "My content" section
    case 'views-exposed-form-og-my-content-page-2':
    // The "All Content" tab on the "My content" section
    case 'views-exposed-form-og-my-content-page-1':
    // The "Recent group content" block found on group home pages
    case 'views-exposed-form-og-content-tracker-panel-pane-1':
      // The exposed filter for node type contains all nodes on the site
      // We want to limit it to group post types only
      if (isset($form['type'])) {
        foreach ($form['type']['#options'] as $type => $name) {
          if ($type != 'All' && !og_is_group_post_type($type)) {
            unset($form['type']['#options'][$type]);
          }
        }
      }
      break;
  }
}

// COMMENT OVERRIDES

/*
 * Minor override and alteration of comment_edit()
 * 
 * Allows group admins to edit comments in their group
 */
function commons_core_comment_edit($cid) {
  global $user;

  $comment = db_fetch_object(db_query('SELECT c.*, u.uid, u.name AS registered_name, u.data FROM {comments} c INNER JOIN {users} u ON c.uid = u.uid WHERE c.cid = %d', $cid));
  $comment = drupal_unpack($comment);
  $comment->name = $comment->uid ? $comment->registered_name : $comment->name;
  
  // See if the user can edit the comment
  if (commons_core_can_edit_comment($comment)) {
    // We need to use our own comment form now
    return theme('box', NULL, drupal_get_form('commons_core_comment_form', (array)$comment, NULL));  
  }
  
  // If none of the above, fall back on what comment.module normally uses
  if (comment_access('edit', $comment)) {
    return comment_form_box((array)$comment);
  }
  else {
    drupal_access_denied();
  }
}

/*
 * Copied from comment_form()
 * 
 * We need to remove the check for administer comments permissions
 * because at this point, the current user is the group admin for the
 * node being comment on. We want to allow full edit access.
 */
function commons_core_comment_form(&$form_state, $edit, $title = NULL) {
  global $user;

  $op = isset($_POST['op']) ? $_POST['op'] : '';
  $node = node_load($edit['nid']);

  if (!$user->uid && variable_get('comment_anonymous_'. $node->type, COMMENT_ANONYMOUS_MAYNOT_CONTACT) != COMMENT_ANONYMOUS_MAYNOT_CONTACT) {
    drupal_add_js(drupal_get_path('module', 'comment') .'/comment.js');
  }
  $edit += array('name' => '', 'mail' => '', 'homepage' => '');
  if ($user->uid) {
    // The check for administer comments was removed from here
    // We must trust the user if they've reached this form
    if (!empty($edit['cid'])) {
      if (!empty($edit['author'])) {
        $author = $edit['author'];
      }
      elseif (!empty($edit['name'])) {
        $author = $edit['name'];
      }
      else {
        $author = $edit['registered_name'];
      }

      if (!empty($edit['status'])) {
        $status = $edit['status'];
      }
      else {
        $status = 0;
      }

      if (!empty($edit['date'])) {
        $date = $edit['date'];
      }
      else {
        $date = format_date($edit['timestamp'], 'custom', 'Y-m-d H:i O');
      }

      $form['admin'] = array(
        '#type' => 'fieldset',
        '#title' => t('Administration'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#weight' => -2,
      );

      if ($edit['registered_name'] != '') {
        // The comment is by a registered user
        $form['admin']['author'] = array(
          '#type' => 'textfield',
          '#title' => t('Authored by'),
          '#size' => 30,
          '#maxlength' => 60,
          '#autocomplete_path' => 'user/autocomplete',
          '#default_value' => $author,
          '#weight' => -1,
        );
      }
      else {
        // The comment is by an anonymous user
        $form['is_anonymous'] = array(
          '#type' => 'value',
          '#value' => TRUE,
        );
        $form['admin']['name'] = array(
          '#type' => 'textfield',
          '#title' => t('Authored by'),
          '#size' => 30,
          '#maxlength' => 60,
          '#default_value' => $author,
          '#weight' => -1,
        );
        $form['admin']['mail'] = array(
          '#type' => 'textfield',
          '#title' => t('E-mail'),
          '#maxlength' => 64,
          '#size' => 30,
          '#default_value' => $edit['mail'],
          '#description' => t('The content of this field is kept private and will not be shown publicly.'),
        );

        $form['admin']['homepage'] = array(
          '#type' => 'textfield',
          '#title' => t('Homepage'),
          '#maxlength' => 255,
          '#size' => 30,
          '#default_value' => $edit['homepage'],
        );
      }

      $form['admin']['date'] = array('#type' => 'textfield', '#parents' => array('date'), '#title' => t('Authored on'), '#size' => 20, '#maxlength' => 25, '#default_value' => $date, '#weight' => -1);

      $form['admin']['status'] = array('#type' => 'radios', '#parents' => array('status'), '#title' => t('Status'), '#default_value' =>  $status, '#options' => array(t('Published'), t('Not published')), '#weight' => -1);

    }
    else {
      $form['_author'] = array('#type' => 'item', '#title' => t('Your name'), '#value' => theme('username', $user)
      );
      $form['author'] = array('#type' => 'value', '#value' => $user->name);
    }
  }
  else if (variable_get('comment_anonymous_'. $node->type, COMMENT_ANONYMOUS_MAYNOT_CONTACT) == COMMENT_ANONYMOUS_MAY_CONTACT) {
    $form['name'] = array('#type' => 'textfield', '#title' => t('Your name'), '#maxlength' => 60, '#size' => 30, '#default_value' => $edit['name'] ? $edit['name'] : variable_get('anonymous', t('Anonymous'))
    );

    $form['mail'] = array('#type' => 'textfield', '#title' => t('E-mail'), '#maxlength' => 64, '#size' => 30, '#default_value' => $edit['mail'], '#description' => t('The content of this field is kept private and will not be shown publicly.')
    );

    $form['homepage'] = array('#type' => 'textfield', '#title' => t('Homepage'), '#maxlength' => 255, '#size' => 30, '#default_value' => $edit['homepage']);
  }
  else if (variable_get('comment_anonymous_'. $node->type, COMMENT_ANONYMOUS_MAYNOT_CONTACT) == COMMENT_ANONYMOUS_MUST_CONTACT) {
    $form['name'] = array('#type' => 'textfield', '#title' => t('Your name'), '#maxlength' => 60, '#size' => 30, '#default_value' => $edit['name'] ? $edit['name'] : variable_get('anonymous', t('Anonymous')), '#required' => TRUE);

    $form['mail'] = array('#type' => 'textfield', '#title' => t('E-mail'), '#maxlength' => 64, '#size' => 30, '#default_value' => $edit['mail'], '#description' => t('The content of this field is kept private and will not be shown publicly.'), '#required' => TRUE);

    $form['homepage'] = array('#type' => 'textfield', '#title' => t('Homepage'), '#maxlength' => 255, '#size' => 30, '#default_value' => $edit['homepage']);
  }

  if (variable_get('comment_subject_field_'. $node->type, 1) == 1) {
    $form['subject'] = array('#type' => 'textfield', '#title' => t('Subject'), '#maxlength' => 64, '#default_value' => !empty($edit['subject']) ? $edit['subject'] : '');
  }

  if (!empty($edit['comment'])) {
    $default = $edit['comment'];
  }
  else {
    $default = '';
  }

  $form['comment_filter']['comment'] = array(
    '#type' => 'textarea',
    '#title' => t('Comment'),
    '#rows' => 15,
    '#default_value' => $default,
    '#required' => TRUE,
  );
  if (!isset($edit['format'])) {
    $edit['format'] = FILTER_FORMAT_DEFAULT;
  }
  $form['comment_filter']['format'] = filter_form($edit['format']);

  $form['cid'] = array('#type' => 'value', '#value' => !empty($edit['cid']) ? $edit['cid'] : NULL);
  $form['pid'] = array('#type' => 'value', '#value' => !empty($edit['pid']) ? $edit['pid'] : NULL);
  $form['nid'] = array('#type' => 'value', '#value' => $edit['nid']);
  $form['uid'] = array('#type' => 'value', '#value' => !empty($edit['uid']) ? $edit['uid'] : 0);

  // Only show save button if preview is optional or if we are in preview mode.
  // We show the save button in preview mode even if there are form errors so that
  // optional form elements (e.g., captcha) can be updated in preview mode.
  if (!form_get_errors() && ((variable_get('comment_preview_'. $node->type, COMMENT_PREVIEW_REQUIRED) == COMMENT_PREVIEW_OPTIONAL) || ($op == t('Preview')) || ($op == t('Save')))) {
    $form['submit'] = array('#type' => 'submit', '#value' => t('Save'), '#weight' => 19);
  }

  $form['preview'] = array('#type' => 'button', '#value' => t('Preview'), '#weight' => 20);
  $form['#token'] = 'comment'. $edit['nid'] . (isset($edit['pid']) ? $edit['pid'] : '');

  if ($op == t('Preview')) {
    $form['#after_build'] = array('comment_form_add_preview');
  }

  if (empty($edit['cid']) && empty($edit['pid'])) {
    $form['#action'] = url('comment/reply/'. $edit['nid']);
  }

  return $form;
}

/*
 * Implementation of hook_link_alter()
 */
function commons_core_link_alter(&$links, $node, $comment = NULL) {
  global $user;
  
  // Only act on comment links
  if ($comment) {
    // Only check if the edit link is missing
    if (!isset($links['comment_edit'])) {
      // Check if user can edit the comment
      if (commons_core_can_edit_comment($comment)) {
        // Provide an edit link
        $link['comment_edit'] = array(
          'title' => t('edit'),
          'href' => 'comment/edit/' . $comment->cid,
        );
        
        // Add link to the beginning
        $links = $link + $links;
      }
    }
  }
}

/*
 * Determine whether a user can edit a comment
 * 
 * This is determined by the checking the group which the comment
 * belongs to via it's parent node. If the current user is an admin
 * of the group, they can edit
 *
 * @param $comment
 *   A comment object
 * @return
 *   TRUE if the user is allowed to edit, otherwise FALSE
 */
function commons_core_can_edit_comment($comment) {
  global $user;
  
  // Are we allowing group admins to edit comments?
  if (variable_get('commons_group_admin_edit_comments', 0)) {
    // Which groups are this comments in?
    if ($groups = og_get_node_groups(node_load($comment->nid))) {
      foreach ($groups as $id => $group) {
        // If user is the admin of at least one group, allow edit comment
        if (og_is_group_admin(node_load($id), $user)) {
          return TRUE;
        }
      }  
    }
  }
  
  return FALSE;
}

/**
 * Implementation of hook_user()
 */
function commons_core_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'view' ) {
    // Remove the "subscribe to" link because we're providing
    // a custom block for that to be placed elsewhere
    unset($account->content['summary']['notifications']);
  }
}

/**
* Implementation of hook_action_info().
*/
function commons_core_action_info() {
  return array(
    // Provide a "Mark as read" action for VBO
    'commons_core_noderead_action' => array(
      'description' => t('Mark as read'),
      'type' => 'node',
      'configurable' => FALSE,
      'hooks' => array(
        'nodeapi' => array('presave'),
        'comment' => array('insert', 'update'),  
      )    
    ),
    // Provide a "Mark as unread" action for VBO
    'commons_core_nodeunread_action' => array(
      'description' => t('Mark as unread'),
      'type' => 'node',
      'configurable' => FALSE,
      'hooks' => array(
        'nodeapi' => array('presave'),
        'comment' => array('insert', 'update'),  
      )    
    )
  );
}

/**
 * Set a given node as read for the current user
 * 
 * @see
 *   commons_core_action_info()
 */
function commons_core_noderead_action(&$node) {
  global $user;

  if ($user->uid) {
    // Remove any records for this node for this user
    db_query("DELETE FROM {history} WHERE nid = %d AND uid = %d", $node->nid, $user->uid);
    
    // Add a record showing this node was just viewed by this user
    $record = new stdClass;
    $record->nid = $node->nid;
    $record->uid = $user->uid;
    $record->timestamp = time();
    drupal_write_record('history', $record);     
  }     
}

/**
 * Set a given node as unread for the current user
 * 
 * @see
 *   commons_core_action_info()
 */
function commons_core_nodeunread_action(&$node) {
  global $user;

  if ($user->uid) {
    // Remove any records for this node for this user
    db_query("DELETE FROM {history} WHERE nid = %d AND uid = %d", $node->nid, $user->uid);    
  }     
}

// TAGGING

/**
 * Implementation of hook_tagging_suggestions()
 */
function commons_core_tagging_suggestions($vid, $node) {
  $suggestions = array();
  
  // Check if there are suggestions stored
  if ($tags = variable_get('commons_tag_suggestions', '')) {
    $tags = array_reverse(explode(',', $tags));
    foreach ($tags as $tag) {
      $suggestions[] = array(
        '#name' => trim($tag),
      );
    }
  }

  return $suggestions;
}

/**
 * Implementation of hook_form_tagging_admin_settings_alter()
 */
function commons_core_form_tagging_admin_settings_alter(&$form, &$form_state) {
  // Remove checkbox
  unset($form['tagging_show_suggestion_example']);
  
  // Add a field to supply static suggestions
  $form['commons_tag_suggestions'] = array(
    '#type' => 'textarea',
    '#title' => t('Static tag suggestions'),
    '#description' => t('Enter a comma-separated list of terms that will show up as tag suggestions when creating content items.'),
    '#weight' => -5,
    '#default_value' => variable_get('commons_tag_suggestions', ''),
  );
}

/**
 * Implementation of hook_theme()
 */
function commons_core_theme() {
  return array(
    'commons_core_user_stats_block' => array(),
    'commons_core_info_block' => array(),
    'commons_core_node_add_link' => array(
      'arguments' => array('link' => NULL),
    ),
  );
}

/**
 * Theme handler for node add links
 */
function theme_commons_core_node_add_link($link) {
  return '<span class="addnew">' . $link . '</span>';
}

/**
 * Theme handler for user stats block
 */
function theme_commons_core_user_stats_block($data) {
  $content = '<ul>';
  foreach($data as $item) {
    $content .= '<li>' . $item . '</li>';
  }
  $content .= '</ul>';
  
  return $content;
}

/**
 * Display the Commons information block
 * 
 * This is used in the footer to link back to acquia.com
 */
function theme_commons_core_info_block() {
  $content = '';
  
  $content .= '<div id="acquia-footer-message">';

  $content .= '<a href="http://acquia.com/drupalcommons" title="Drupal Commons social business software">';
  $content .= theme('image', 'profiles/drupal_commons/images/commons_droplet.png', t('Drupal Commons social business software'), t('Drupal Commons social business software'));
  $content .= '</a>';
  $content .= '<span>';
  $content .= t('A !dc Community, powered by', array('!dc' => l(t('Drupal Commons'), 'http://acquia.com/drupalcommons', array('attributes' => array('title' => t('A Drupal Commons social business software')))))) . '&nbsp;';
  $content .= l(t('Acquia'), 'http://acquia.com', array('attributes' => array('title' => t('Acquia'))));
  $content .= '</span>';
  $content .= '</div>';
  
  $content .= '<div id="fusion-footer-message">';
  $content .= t('Theme by') . '&nbsp;';
  $content .= '<a href="http://www.topnotchthemes.com" title="Drupal Themes by TopNotchThemes">TopNotchThemes</a>';
  $content .= ', ' . t('powered by') . '&nbsp;';
  $content .= '<a href="http://fusiondrupalthemes.com" title="Premium Drupal themes powered by Fusion">Fusion</a>.';
  $content .= '</div>';
  
  return $content;
}
