<?php

/**
 * Implementation of hook_install()
 */
function acquia_network_subscription_install() {
  module_load_include('inc', 'acquia_network_subscription', 'acquia_network_subscription.strongarm');
  
  // Gather the exported variables
  $vars = acquia_network_subscription_strongarm();
  
  // This needs to be manually set because it's set on install
  variable_set('apachesolr_enabled_facets', $vars['apachesolr_enabled_facets']->value);
}
