<?php

function contextual_search_box_form_search_theme_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'contextual_search_box');
  drupal_add_js($path . '/contextual_search_box.js');
  drupal_add_css($path . '/contextual_search_box.css');
  
  $options = array();
  $group = NULL;

  $menu_item = menu_get_item($_GET['q']);
  if ($key = array_search('node_load', $menu_item['load_functions'])) {
    $node = $menu_item['map'][$key];
    // Do node stuff
    if($group = og_determine_context_get_group($node)) {
      $solr = module_exists('apachesolr_search');
      $group_string = $solr ? 'search/apachesolr_search/!terms?filters=group:' . $group->nid : 'og/search/' . $group->nid . '?keys=!terms';
      if ($solr && $node != $group) {
        $options[$group_string . ' type:' . $node->type] = t('@type posts in @group', array('@type' => ucfirst($node->type), '@group' => $group->title));
      }
      $options[$group_string] = $group->title;
    }
  }
  $options['site'] = t('Entire site');
  $options['user'] = t('People');
  
  $form['refine'] = array(
    '#type' => 'select',
    '#title' => t('within'),
    '#options' => $options,
    '#weight' => 1,
  );
  
  if (!$group) {
    $form['refine']['#default_value'] = in_array('user', $menu_item['map']) ? 'user' : 'site';
  }
  
  $form['submit']['#weight'] = 2;
  $submit = $form['submit'];
  unset($form['submit']);
  $form['submit'] = $submit;
  
  $form['search_theme_form']['#title'] = t('Search');
  $form['#submit'][] = 'commons_roots_search_submit';
}

function commons_roots_search_submit($form, &$form_state) {
  // Copied from search_box_form_submit().
  if (isset($_REQUEST['destination'])) {
    unset($_REQUEST['destination']);
  }
  if (isset($_REQUEST['edit']['destination'])) {
    unset($_REQUEST['edit']['destination']);
  }
  
  $form_id = $form['form_id']['#value'];
  $terms = strpos($form_state['values']['refine'], 'og/search') == 0 ? str_replace(' ', '+', trim($form_state['values'][$form_id])) : trim($form_state['values'][$form_id]);
  $form_state['redirect'] = str_replace('!terms', $terms, $form_state['values']['refine']);
}
