<?php
// $Id: tagging.install,v 1.12.2.6 2010/10/17 10:23:24 eugenmayer Exp $

// Author: Eugen Mayer (http://kontextwork.de)
// Copyright 2010

/**
 * @file
 * Installation/updates for tagging
 */

 /**
 * Implementation of hook_install().
 */
function tagging_install() {
  db_query("UPDATE {system} SET weight = 10 WHERE name = 'tagging'");
}

/**
 * Implementation of hook_uninstall().
 */
function tagging_uninstall(){
  db_query("DELETE from {variable} WHERE name LIKE 'tagging_inject_%'");
}