<?php

include_once('commons_blog.features.inc');

/**
 * Implementation of hook_views_pre_view()
 */
function commons_blog_views_pre_view(&$view, &$display_id, &$args) {
  switch ($view->name) {
    case 'content_global_blogs':
      $view->display_handler->override_option('header', commons_core_node_add_link('blog'));
      break;
  }
}

/**
 * Implementation of hook_og_features_registry()
 */
function commons_blog_og_features_registry() {
  $registry = array();
  
  // Feature: commons_blog
  $feature = new stdClass;
  $feature->id = 'commons_blog';
  $feature->name = t('Blog');
  $feature->description = t('Provide a simple blog for your group');
  $feature->components = array(
    'views' => array(
      'group_tab_blogs',
    ),
    'node' => array(
      'blog',
    ),
    'context' => array(
      'context_ui-group-group-home-blogs',
      'context_ui-group-group-tab-blogs',
    ),
  );
  $registry[$feature->id] = $feature;
  
  return $registry;
}
