<?php

include_once('commons_discussion.features.inc');

/**
 * Implementation of hook_views_pre_view()
 */
function commons_discussion_views_pre_view(&$view, &$display_id, &$args) {
  switch ($view->name) {
    case 'content_global_discussions':
      $view->display_handler->override_option('header', commons_core_node_add_link('discussion'));
      break;
  }
}

/**
 * Implementation of hook_og_features_registry()
 */
function commons_discussion_og_features_registry() {
  $registry = array();
  
  // Feature: commons_discussion
  $feature = new stdClass;
  $feature->id = 'commons_discussion';
  $feature->name = t('Discussions');
  $feature->description = t('Provide a space for discussions for your group');
  $feature->components = array(
    'views' => array(
      'group_tab_discussions',
    ),
    'node' => array(
      'discussion',
    ),
    'context' => array(
      'context_ui-group-group-home-discussions',
      'context_ui-group-group-tab-discussions',
    ),
  );
  $registry[$feature->id] = $feature;
  
  return $registry;
}
